### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by AlanCh4n** [kickz1997/discord.js-Moderation-Bot#4]
![image](https://user-images.githubusercontent.com/70933452/99792252-07509900-2b51-11eb-94bd-1aa5ccea2d6b.png)
pls help me

**Comment by eshansalimi** [comment]
Have you figured it out? First off, it looks like you haven’t entered information in your `config.json` file, so put your token and your personal Discord User ID in there.

**Comment by AlanCh4n** [comment]
> Have you figured it out? First off, it looks like you haven’t entered information in your `config.json` file, so put your token and your personal Discord User ID in there.

oh hey! uhh actually, I didnt know much coding back then. so it was hard for me to figure out the errors. now I know how to fix these, and I actualy dont need help from other repos anymore
anyways, thx for trying to help :)

**Comment by DeathHound6** [comment]
Hey @AlanCh4n! Do you still need help with this?

**Comment by AlanCh4n** [comment]
> Hey @AlanCh4n! Do you still need help with this?

nope
